modLoader="javafml"
loaderVersion="[45,)"
license="MIT"
issueTrackerURL="https://github.com/ochotonida/gardens-of-the-dead/issues"

[[mods]]
modId="gardens_of_the_dead"
version="${version}"
displayName="Gardens of the Dead"
displayURL="https://www.curseforge.com/minecraft/mc-mods/gardens-of-the-dead"
logoFile="logo.png"
authors="ochotonida"

description='''Adds new spooky biomes to the Nether. Created for Spooky Jam 2022.'''

[[dependencies.gardens_of_the_dead]]
modId="forge"
mandatory=true
versionRange="[45,)"
ordering="NONE"
side="BOTH"

[[dependencies.gardens_of_the_dead]]
modId="minecraft"
mandatory=true
versionRange="[1.19.4,1.20)"
ordering="NONE"
side="BOTH"

[[dependencies.gardens_of_the_dead]]
modId = "architectury"
mandatory = true
versionRange = "[8.1.79,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.gardens_of_the_dead]]
modId="terrablender"
mandatory=true
versionRange="[2.2.0.155,)"
ordering="NONE"
side="BOTH"
