modLoader="javafml"
loaderVersion="[46,)"
license="MIT"
issueTrackerURL="https://github.com/ochotonida/gardens-of-the-dead/issues"

[[mods]]
modId="gardens_of_the_dead"
version="${version}"
displayName="Gardens of the Dead"
displayURL="https://www.curseforge.com/minecraft/mc-mods/gardens-of-the-dead"
logoFile="logo.png"
authors="ochotonida"

description='''Adds new spooky biomes to the Nether. Created for Spooky Jam 2022.'''

[[dependencies.gardens_of_the_dead]]
modId="forge"
mandatory=true
versionRange="[46,)"
ordering="NONE"
side="BOTH"

[[dependencies.gardens_of_the_dead]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.gardens_of_the_dead]]
modId = "architectury"
mandatory = true
versionRange = "[9.0.7,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.gardens_of_the_dead]]
modId="terrablender"
mandatory=true
versionRange="[3.0.0.163,)"
ordering="NONE"
side="BOTH"
