modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
issueTrackerURL="https://github.com/ochotonida/gardens-of-the-dead/issues"

[[mods]]
modId="gardens_of_the_dead"
version="${file.jarVersion}"
displayName="Gardens of the Dead"
displayURL="https://www.curseforge.com/minecraft/mc-mods/gardens-of-the-dead"
# TODO logoFile="logo.png"
authors="ochotonida"

description='''Adds new spooky biomes to the Nether. Made for Spooky Jam 2022.'''

[[dependencies.gardens_of_the_dead]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.gardens_of_the_dead]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.gardens_of_the_dead]]
    modId="terrablender"
    mandatory=true
    versionRange="[2.0.1.127,)"
    ordering="NONE"
    side="BOTH"
